import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Hello Next.js",
  description: "Generated by create next app",
};

const Page = () => {
  throw new Error("Not implemented");
  return (
    <div>About</div>
  );
}

export default Page;
